// This file has been autogenerated from a class added in the UI designer.

using System;
using Autofac;
using Foundation;
using OfflineFirstReferenceArch.ViewModels;
using UIKit;

namespace OfflineFirstReferenceArch.IOS
{
	public partial class LandingPageViewController : UIViewController
	{
	    private LandingPageViewModel _viewModel;

	    public LandingPageViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            _viewModel = DIContainer.ContainerInstance.Resolve<LandingPageViewModel>();
            _viewModel.Initialize();
        }
    }
}
